BizzDesk-Leap-Client/Areas/HRAdmin/ViewModels/LeaveTypeViewModel.cs
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels
{
    public class LeaveTypeViewModel
    {
        public LeaveType LeaveType
        { 
            get;
            set; 
        }
    }
}

BizzDesk-Leap-Client/Areas/HRAdmin/Controllers/LeaveTypeController.cs
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BizzDesk_Leap_Client.Areas.HRAdmin.Controllers
{
    public class LeaveTypeController : Controller
    {
        LeaveTypeClient ltc;
        RankClient rc;
        DepartmentClient dc;
        public LeaveTypeController()
        {
            ltc = new LeaveTypeClient();
            rc = new RankClient();
            dc = new DepartmentClient();
        }

        //
        // GET: /HRAdmin/LeaveType/
        public ActionResult Index()
        {
            ViewBag.Types = ltc.findAll().OrderBy(s => s.Title); 
            return View();
        }

        //
        // GET: /HRAdmin/LeaveType/Create
        [HttpGet]
        public ActionResult Create()
        {
            var leavetype = new LeaveTypeViewModel();
            ViewBag.Department = new SelectList(dc.findAll(), "ID", "Title");
            ViewBag.Rank = new SelectList(rc.findAll(), "ID", "Title");
            return PartialView("Create", leavetype);
        }

        //
        // POST: /HRAdmin/LeaveType/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LeaveTypeViewModel leavetype)
        {
            if (ModelState.IsValid)
            {
                ltc.Create(leavetype.LeaveType);
                ViewBag.Department = new SelectList(dc.findAll(), "ID", "Title", leavetype.LeaveType.DepartmentID);
                ViewBag.Rank = new SelectList(rc.findAll(), "ID", "Title", leavetype.LeaveType.RankID);
                return Json(new { success = true });
            }
            return PartialView("Create", leavetype);
        }

        //
        // GET: /HRAdmin/LeaveType/Edit/id
        [HttpGet]
        public ActionResult Edit(int id)
        {
            LeaveTypeViewModel leavetype = new LeaveTypeViewModel();
            leavetype.LeaveType = ltc.find(id);
            ViewBag.Department = new SelectList(dc.findAll(), "ID", "Title", leavetype.LeaveType.DepartmentID);
            ViewBag.Rank = new SelectList(rc.findAll(), "ID", "Title", leavetype.LeaveType.RankID);
            return PartialView("Edit", leavetype);
        }

        //
        // POST: /HRAdmin/LeaveType/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LeaveTypeViewModel leavetype)
        {
            if (ModelState.IsValid)
            {
                ltc.Edit(leavetype.LeaveType);
                ViewBag.Department = new SelectList(dc.findAll(), "ID", "Title", leavetype.LeaveType.DepartmentID);
                ViewBag.Rank = new SelectList(rc.findAll(), "ID", "Title", leavetype.LeaveType.RankID);
                return Json(new { success = true });
            }
            return PartialView("Edit", leavetype);
        }

        //
        // POST: /HRAdmin/LeaveType/Delete/id
        public ActionResult Delete(int id)
        {
            ltc.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Constraint(int id)
        {
            LeaveTypeViewModel leavetype = new LeaveTypeViewModel();
            leavetype.LeaveType = ltc.find(id);
            return PartialView("Constraints", leavetype);
        }
	}
}

BizzDesk-Leap-Client/Areas/HRAdmin/Views/LeaveType/Constraints.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels.LeaveTypeViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><b>Leave Type Constraints</b></h4>
</div>
    <div class="modal-body">
        <dl class="dl-horizontal">
                <dt> Gender </dt>
                <dd> @Html.DisplayFor(model => model.LeaveType.GenderConstraint)</dd>
                <dt> Department: </dt>
                <dd> @Html.DisplayFor(model => model.LeaveType.DepartmentConstraint.Title)</dd>
                <dt> Rank: </dt>
                <dd> @Html.DisplayFor(model => model.LeaveType.RankConstraint.Title)</dd>
        </dl>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
    </div>

BizzDesk-Leap-Client/Areas/HRAdmin/Views/LeaveType/Create.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels.LeaveTypeViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><b>Create Leave Type</b></h4>
</div>

@using (Html.BeginForm("Create", "LeaveType", new { Area = "HRAdmin" }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                <label for="title" class="control-label col-sm-3"> Title </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.LeaveType.Title, new { @class = "form-control border-input required", @id = "title" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.Title)
                    </div>
                </div>
            </div>

            <hr />
            <div class="form-group">
                <p class="control-label col-sm-3"><strong>CONSTRAINTS</strong></p>
            </div>
            <br />

            <div class="form-group">
                <label for="gender" class="control-label col-sm-3"> Gender </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.LeaveType.GenderConstraint, new { @class = "form-control border-input", @id = "gender" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.GenderConstraint)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="dept" class="control-label col-sm-3"> Department </label>
                <div class="col-sm-9">
                    @Html.DropDownListFor(model => model.LeaveType.DepartmentID, (IEnumerable<SelectListItem>)ViewBag.Department, string.Empty, new { @class = "form-control border-input", @id = "department" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.DepartmentID)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="rank" class="control-label col-sm-3"> Rank </label>
                <div class="col-sm-9">
                    @Html.DropDownListFor(model => model.LeaveType.RankID, (IEnumerable<SelectListItem>)ViewBag.Rank, string.Empty, new { @class = "form-control border-input", @id = "rank" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.RankID)
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>

        <span id="progress" class="text-center" style="display:none">
            <strong>Processing..</strong>
        </span>

        <input type="submit" class="btn btn-outline" value="Save" />
    </div>
}

<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

BizzDesk-Leap-Client/Areas/HRAdmin/Views/LeaveType/Edit.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels.LeaveTypeViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><b>Edit Leave Type - @Model.LeaveType.Title </b></h4>
</div>

@using (Html.BeginForm("Create", "LeaveType", new { Area = "HRAdmin" }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.LeaveType.ID)

    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                <label for="title" class="control-label col-sm-3"> Title </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.LeaveType.Title, new { @class = "form-control border-input required", @id = "title" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.Title)
                    </div>
                </div>
            </div>

            <hr />
            <div class="form-group">
                <p class="control-label col-sm-3"><strong>CONSTRAINTS</strong></p>
            </div>
            <br />

            <div class="form-group">
                <label for="gender" class="control-label col-sm-3"> Gender </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.LeaveType.GenderConstraint, new { @class = "form-control border-input required", @id = "gender" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.GenderConstraint)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="dept" class="control-label col-sm-3"> Department </label>
                <div class="col-sm-9">
                    @Html.DropDownListFor(model => model.LeaveType.DepartmentID, (IEnumerable<SelectListItem>)ViewBag.Department, string.Empty, new { @class = "form-control border-input", @id = "department" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.DepartmentID)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="rank" class="control-label col-sm-3"> Rank </label>
                <div class="col-sm-9">
                    @Html.DropDownListFor(model => model.LeaveType.RankID, (IEnumerable<SelectListItem>)ViewBag.Rank, string.Empty, new { @class = "form-control border-input", @id = "rank" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.LeaveType.RankID)
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>

        <span id="progress" class="text-center" style="display:none">
            <strong>Processing..</strong>
        </span>

        <input type="submit" class="btn btn-outline" value="Save" />
    </div>
}

<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

BizzDesk-Leap-Client/Areas/HRAdmin/Views/LeaveType/Index.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels.LeaveTypeViewModel

@{
    ViewBag.Title = "Leave Types";
    int x = 1;
}

@section menu{
    <li><a href="@Url.Action("Index", "Dashboard", new { Area = "HRAdmin"})"><i class="fa fa-arrow-left"></i> <span>Return to Dashboard</span></a></li>
    <li class="active">
        <a href="@Url.Action("Index", "LeaveType", new { Area = "HRAdmin"})">
            <i class="fa fa-files-o"></i> <span>Leave Types</span>
        </a>
    </li>
}

<section class="content-header">
    <h1> @ViewBag.Title </h1>

    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="fa fa-dashboard"></i>
                Home
            </a>
        </li>
        <li class="active">
            <a href="@Url.Action("Index", "LeaveType", new { Area = "HRAdmin"})">
                <i class="fa fa-files-o"></i>
                Leave Types
            </a>
        </li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>

                    <div class="pull-left">
                        <a class="btn btn-info btn-sm" data-modal="" href="@Url.Action("Create", "LeaveType", new { Area = "HRAdmin"})"><i class="fa fa-plus"></i> Create Leave Type</a>
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
                    <table class="table table-hover" id="grid">
                        <thead>
                            <tr>
                                <th>S/N</th>
                                <th>Title</th>
                                <th>Options</th>
                            </tr>
                        </thead>

                        @if (ViewBag.Types != null)
                        {
                            foreach (var type in ViewBag.Types)
                            {
                                <tr>
                                    <td>@(x++)</td>
                                    <td>@type.Title</td>
                                    <td>
                                        <a class="btn btn-success btn-xs" data-modal="" href="@Url.Action("Edit", "LeaveType", new { Area = "HRAdmin", id = type.ID })"><i class="fa fa-pencil"></i> Edit </a>
                                        <a class="btn btn-danger btn-xs delete" href="@Url.Action("Delete", "LeaveType", new { Area = "HRAdmin", id = type.ID})"><i class="fa fa-trash"></i> Delete </a>
                                        <a class="btn btn-info btn-xs" data-modal="" href="@Url.Action("Constraint", "LeaveType", new { Area = "HRAdmin", id = type.ID})"><i class="fa fa-folder-open"></i> View Constraints </a>
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

    <!-- modal placeholder-->
    <div id='myModal' class='modal modal-primary fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-content" id='myModalContent'></div>
            </div>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript" src="~/Scripts/modal.js"></script>
        <script type="text/javascript" src="~/Scripts/delete-modal.js"></script>
        <script>
            $(document).ready(function () {
                $('#grid').DataTable({
                    columnDefs: [
                        {
                            targets: [0, 1, 2],
                            className: 'dataTable'
                        }
                    ]
                });
            });
        </script>
    }
</section>