BizzDesk-Leap-Client/Areas/Employee/Models/Request.cs
using BizzDesk_Leap_Client.Areas.Employee.Enums;
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.Employee.Models
{
    public class Request
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Select start date")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "Select end date")]
        public DateTime EndDate { get; set; }

        [Required]
        public DateTime RequestDate { get; set; }

        public Status Status { get; set; }

        //Entity Relationships

        [ForeignKey("Employee")]
        public int EmployeeID { get; set; }

        public virtual BizzDesk_Leap_Client.Areas.HRAdmin.Models.Employee Employee { get; set; }

        [Required]
        public int LeaveID { get; set; }

        public virtual Leave Leave { get; set; }
    }
}

BizzDesk-Leap-Client/Areas/Employee/ViewModels/RequestViewModel.cs
using BizzDesk_Leap_Client.Areas.Employee.Enums;
using BizzDesk_Leap_Client.Areas.Employee.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.Employee.ViewModels
{
    public class RequestViewModel
    {
        public Request Request
        {
            get;
            set;
        }

        public Status Status
        {
            get;
            set;
        }
    }
}

BizzDesk-Leap-Client/Areas/Employees/Models/Request.cs
using BizzDesk_Leap_Client.Areas.Employees.Enums;
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.Employees.Models
{
    public class Request
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Select start date")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "Select end date")]
        public DateTime EndDate { get; set; }

        [Required]
        public DateTime RequestDate { get; set; }

        public Status Status { get; set; }

        //Entity Relationships

        [ForeignKey("Employee")]
        public int EmployeeID { get; set; }

        public virtual Employee Employee { get; set; }

        [Required]
        public int LeaveID { get; set; }

        public virtual Leave Leave { get; set; }
    }
}

BizzDesk-Leap-Client/Areas/Employees/ViewModels/RequestViewModel.cs
using BizzDesk_Leap_Client.Areas.Employees.Enums;
using BizzDesk_Leap_Client.Areas.Employees.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.Employees.ViewModels
{
    public class RequestViewModel
    {
        public Request Request
        {
            get;
            set;
        }

        public Status Status
        {
            get;
            set;
        }
    }
}

BizzDesk-Leap-Client/Areas/Employee/Controllers/RequestController.cs
using BizzDesk_Leap_Client.Areas.Employee.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BizzDesk_Leap_Client.Areas.Employee.ViewModels;
using BizzDesk_Leap_Client.Controllers;
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using System.Net.Http;
using System.Net.Http.Headers;

namespace BizzDesk_Leap_Client.Areas.Employee.Controllers
{
    public class RequestController : BaseController
    {
        LeaveClient lc;
        RequestViewModel rvm;

        public RequestController()
        {
            rc = new RequestClient();
            lc = new LeaveClient();
            rvm = new RequestViewModel();
        }

        // GET: /Employee/Request/
        public ActionResult Index(int? page)
        {
            var id = Convert.ToInt32(Session["ID"]);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Leaves = new SelectList(lc.findAll(), "ID", "Title");
            var rvm = new RequestViewModel();
            return PartialView("Create", rvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RequestViewModel rvm)
        {
            if (ModelState.IsValid)
            {
                rc.Create(rvm.Request);
                return Json(new { success = true });
            }
            ViewBag.Leaves = new SelectList(lc.findAll(), "ID", "Title", rvm.Request.LeaveID);
            return PartialView("Create", rvm);
        }
	}
}

BizzDesk-Leap-Client/Areas/Employees/Controllers/RequestController.cs
using BizzDesk_Leap_Client.Areas.Employees.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BizzDesk_Leap_Client.Areas.Employees.ViewModels;
using BizzDesk_Leap_Client.Controllers;
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using System.Net.Http;
using System.Net.Http.Headers;

namespace BizzDesk_Leap_Client.Areas.Employees.Controllers
{
    public class RequestController : BaseController
    {
        LeaveClient lc;
        RequestViewModel rvm;
        RequestClient rc;

        public RequestController()
        {
            rc = new RequestClient();
            lc = new LeaveClient();
            rvm = new RequestViewModel();
        }

        // GET: /Employee/Request/
        public ActionResult Index(int? page)
        {
            var id = Convert.ToInt32(Session["ID"]);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.Requests = rc.findAll().Where(s => s.EmployeeID == id).OrderByDescending(s => s.RequestDate).ToPagedList(pageNumber, pageSize);
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Leaves = new SelectList(lc.findAll(), "ID", "Title");
            var rvm = new RequestViewModel();
            return PartialView("Create", rvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RequestViewModel rvm)
        {
            if (ModelState.IsValid)
            {
                rc.Create(rvm.Request);
                return Json(new { success = true });
            }
            ViewBag.Leaves = new SelectList(lc.findAll(), "ID", "Title", rvm.Request.LeaveID);
            return PartialView("Create", rvm);
        }
	}
}

BizzDesk-Leap-Client/Areas/HRAdmin/Controllers/RequestController.cs
using BizzDesk_Leap_Client.Areas.Employees.Models;
using BizzDesk_Leap_Client.Areas.Employees.Enums;
using BizzDesk_Leap_Client.Areas.Employees.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;

namespace BizzDesk_Leap_Client.Areas.HRAdmin.Controllers
{
    public class RequestController : Controller
    {
        RequestViewModel rvm;
        RequestClient rc;
        DepartmentClient dc;
        RankClient rkc;
        EmployeeClient ec;
        LeaveClient lc;
        RoleClient roc;

        public RequestController()
        {
            rc = new RequestClient();
            rvm = new RequestViewModel();

            dc = new DepartmentClient();
            rkc = new RankClient();
            ec = new EmployeeClient();
            lc = new LeaveClient();
            roc = new RoleClient();

            ViewBag.DepartmentCount = dc.findAll().ToArray().Length;
            ViewBag.RankCount = rkc.findAll().ToArray().Length;
            ViewBag.EmployeeCount = ec.findAll().ToArray().Length;
            ViewBag.LeaveCount = lc.findAll().ToArray().Length;
            ViewBag.RoleCount = roc.findAll().ToArray().Length;
            ViewBag.RequestCount = rc.findAll().Where(s => s.Status == Status.Pending && s.EndDate > DateTime.Now).ToArray().Length;
        }

        //
        // GET: /HRAdmin/Request/
        public ActionResult Index()
        {
            ViewBag.Requests = rc.findAll().OrderByDescending(s => s.RequestDate);
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            RequestViewModel rvm = new RequestViewModel();
            rvm.Request = rc.find(id);
            return PartialView("Details", rvm); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(RequestViewModel rvm)
        {
            if (ModelState.IsValid)
            {
                rc.Edit(rvm.Request);
                return Json(new { success = true });
            }
            return PartialView("Details", rvm);
        }
	}
}

BizzDesk-Leap-Client/Areas/Employees/Views/Request/Create.cshtml
@model BizzDesk_Leap_Client.Areas.Employees.ViewModels.RequestViewModel
@using BizzDesk_Leap_Client.Areas.Employees.Enums

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><b>Request a Leave</b></h4>
</div>

@using (Html.BeginForm("Create", "Request", new { Area = "Employees" }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    @Html.Hidden("Request.EmployeeID", Convert.ToInt32(Session["ID"]))
    @Html.Hidden("Request.Status", Status.Pending)
    @Html.Hidden("Request.RequestDate", DateTime.Now)
    
    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                <label for="leaves" class="control-label col-sm-3"> Leave </label>
                <div class="col-sm-9">
                    @Html.DropDownListFor(model => model.Request.LeaveID, (IEnumerable<SelectListItem>)ViewBag.Leaves, string.Empty, new { @class = "form-control border-input", @id = "leaves" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Request.LeaveID)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3" for="start">Start Date</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Request.StartDate, "{0:dd/MMM/yyyy}", new { @class = "form-control required", @id = "start", @type = "datetime" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Request.StartDate)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3" for="end">End Date</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Request.EndDate, "{0:dd/MMM/yyyy}", new { @class = "form-control required", @id = "end", @type = "datetime" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Request.EndDate)
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>

        <span id="progress" class="text-center" style="display:none">
            <strong>Processing..</strong>
        </span>

        <input type="submit" class="btn btn-outline" value="Save" />
    </div>
}

<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

<script>
    $(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "dd/M/yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "1960:2020"
        });
    });
</script>

BizzDesk-Leap-Client/Areas/Employees/Views/Request/Index.cshtml
@model BizzDesk_Leap_Client.Areas.Employees.Models.RequestClient
@using BizzDesk_Leap_Client.Areas.Employees.Enums
@using PagedList;
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Leave Requests";
    int x = 1;
}

@section menu{
    <li class="#"><a href="@Url.Action("Index", "Dashboard", new { Area = "Employees"})"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
    <li class="active"><a href="@Url.Action("Index", "Request", new { Area = "Employees"})"><i class="fa fa-paper-plane"></i> <span>Leave Requests</span></a></li>
}

<section class="content-header">
    <h1> @ViewBag.Title </h1>

    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="fa fa-dashboard"></i>
                Home
            </a>
        </li>
        <li class="active">
            <a href="@Url.Action("Index", "Request", new { Area = "Employees"})">
                <i class="fa fa-paper-plane"></i>
                Leave Requests
            </a>
        </li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <div class="pull-left">
                        <a class="btn btn-info btn-sm" data-modal="" href="@Url.Action("Create", "Request", new { Area = "Employees"})"><i class="fa fa-rocket"></i> Request a Leave</a>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th></th>
                            <th>S/N</th>
                            <th>Title</th>
                            <th>Type</th>
                            <th>Request Date</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Status</th>
                        </tr>
                            
                        @foreach (var request in ViewBag.Requests)
                            {
                                <tr>
                                    <td></td>
                                    <td>@(x++)</td>
                                    <td>@request.Leave.Title</td>
                                    <td>@request.Leave.LeaveType</td>
                                    <td>@request.RequestDate.ToLongDateString()</td>
                                    <td>@request.StartDate.ToLongDateString()</td>
                                    <td>@request.EndDate.ToLongDateString()</td>
                                    <td>
                                        @if (request.Status == Status.Pending && (DateTime.Now < @request.EndDate))
                                        {
                                            <span class="btn btn-xs btn-warning">@request.Status</span>
                                        }
                                        @if (request.Status == Status.Approved && (DateTime.Now < @request.EndDate))
                                        {
                                            <span class="btn btn-xs btn-success">@request.Status</span>
                                        }
                                        @if (request.Status == Status.Declined)
                                        {
                                            <span class="btn btn-xs btn-danger">@request.Status</span>
                                        }
                                        @if (request.Status == Status.Pending && (DateTime.Now > @request.EndDate))
                                        {
                                            <span class="btn btn-xs btn-danger">Expired</span>
                                        }
                                        @if (request.Status == Status.Approved && (DateTime.Now > @request.EndDate))
                                        {
                                            <span class="btn btn-xs btn-danger">Expired</span>
                                        }
                                    </td>
                                </tr>
                            }
                    </table>
                    <div style="padding-left: 15px">
                        @Html.PagedListPager((IPagedList)ViewBag.Requests, page => Url.Action("Index", "Request", new { Area = "Employees", page }))
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

    <!-- modal placeholder-->
    <div id='myModal' class='modal modal-primary fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-content" id='myModalContent'></div>
            </div>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript" src="~/Scripts/modal.js"></script>
        <script type="text/javascript" src="~/Scripts/delete-modal.js"></script>
    }

</section>