BizzDesk-Leap-Client/Areas/HRAdmin/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.HRAdmin.Models
{
    public class Location
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }

        [Required]
        public string LGA { get; set; }

        [Required]
        public string State { get; set; }
    }
}

BizzDesk-Leap-Client/Areas/HRAdmin/ViewModels/LocationViewModel.cs
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels
{
    public class LocationViewModel
    {
        public Location Location
        {
            get;
            set;
        }
    }
}

BizzDesk-Leap-Client/Areas/HRAdmin/Controllers/LocationController.cs
using BizzDesk_Leap_Client.Areas.HRAdmin.Models;
using BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BizzDesk_Leap_Client.Areas.HRAdmin.Controllers
{
    public class LocationController : Controller
    {
        LocationClient loc;
        public LocationController()
        {
            loc = new LocationClient();
        }

        //
        // GET: /HRAdmin/Location/
        public ActionResult Index()
        {
            ViewBag.Location = loc.findAll().OrderBy(s => s.Title);
            return View();
        }

        //
        // GET: /HRAdmin/Location/Create
        [HttpGet]
        public ActionResult Create() {
            var lovm = new LocationViewModel();
            return PartialView("Create", lovm);
        }

        //
        // POST: /HRAdmin/Location/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LocationViewModel lovm)
        {
            if(ModelState.IsValid)
            {
                loc.Create(lovm.Location);
                return Json(new { success = true });
            }

            return PartialView("Create", lovm);
        }

        //
        // GET: /HRAdmin/Location/Edit/id
        [HttpGet]
        public ActionResult Edit(int id) 
        {
            LocationViewModel lovm = new LocationViewModel();
            lovm.Location = loc.find(id);
            return PartialView("Edit", lovm);
        }

        //
        // POST: /HRAdmin/Location/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LocationViewModel lovm) 
        {
            if (ModelState.IsValid)
            {
                loc.Edit(lovm.Location);
                return Json(new { success = true });
            }
            return PartialView("Edit", lovm);
        }

        //
        // POST: /HRAdmin/Location/Delete/id
        public ActionResult Delete(int id) 
        {
            loc.Delete(id);
            return RedirectToAction("Index");
        }
	}
}

BizzDesk-Leap-Client/Areas/HRAdmin/Views/Location/Create.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels.LocationViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><b>Create Location</b></h4>
</div>

@using (Html.BeginForm("Create", "Location", new { Area = "HRAdmin" }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                <label for="title" class="control-label col-sm-3"> Title </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Location.Title, new { @class = "form-control border-input required", @id = "title" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.Title)
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="state" class="control-label col-sm-3"> State </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Location.State, new { @class = "form-control border-input required", @id = "state" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.State)
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="lga" class="control-label col-sm-3"> LGA </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Location.LGA, new { @class = "form-control border-input required", @id = "lga" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.LGA)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="address" class="control-label col-sm-3"> Address </label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(model => Model.Location.Address, new { @class = "form-control border-input required", @id = "address" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.Address)
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>

        <span id="progress" class="text-center" style="display:none">
            <strong>Processing..</strong>
        </span>

        <input type="submit" class="btn btn-outline" value="Save" />
    </div>
}

<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

BizzDesk-Leap-Client/Areas/HRAdmin/Views/Location/Edit.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.ViewModels.LocationViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><b>Edit Location - @Model.Location.Title</b></h4>
</div>

@using (Html.BeginForm("Edit", "Location", new { Area = "HRAdmin" }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.Location.ID)
    
    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                <label for="title" class="control-label col-sm-3"> Title </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Location.Title, new { @class = "form-control border-input required", @id = "title" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.Title)
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="state" class="control-label col-sm-3"> State </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Location.State, new { @class = "form-control border-input required", @id = "state" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.State)
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="lga" class="control-label col-sm-3"> LGA </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => Model.Location.LGA, new { @class = "form-control border-input required", @id = "lga" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.LGA)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="address" class="control-label col-sm-3"> Address </label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(model => Model.Location.Address, new { @class = "form-control border-input required", @id = "address" })
                    <div class="text-danger">
                        @Html.ValidationMessageFor(model => model.Location.Address)
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>

        <span id="progress" class="text-center" style="display:none">
            <strong>Processing..</strong>
        </span>

        <input type="submit" class="btn btn-outline" value="Save" />
    </div>
}

<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

BizzDesk-Leap-Client/Areas/HRAdmin/Views/Location/Index.cshtml
@model BizzDesk_Leap_Client.Areas.HRAdmin.Models.LocationClient

@{
    ViewBag.Title = "Locations";
    int x = 1;
}

@section menu{
    <li><a href="@Url.Action("Index", "Dashboard", new { Area = "HRAdmin"})"><i class="fa fa-arrow-left"></i> <span>Return to Dashboard</span></a></li>
    <li class="active">
        <a href="@Url.Action("Index", "Location", new { Area = "HRAdmin"})">
            <i class="fa fa-globe"></i> <span>Location</span>
        </a>
    </li>
}

<section class="content-header">
    <h1> @ViewBag.Title </h1>

    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="fa fa-dashboard"></i>
                Home
            </a>
        </li>
        <li class="active">
            <a href="@Url.Action("Index", "Location", new { Area = "HRAdmin"})">
                <i class="fa fa-globe"></i>
                Locations
            </a>
        </li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>

                    <div class="pull-left">
                        <a class="btn btn-info btn-sm" data-modal="" href="@Url.Action("Create", "Location", new { Area = "HRAdmin"})"><i class="fa fa-plus"></i> Create Location</a>
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
                    <table class="table table-hover" id="grid">
                        <thead>
                            <tr>
                                <th>S/N</th>
                                <th>Title</th>
                                <th>Address</th>
                                <th>LGA</th>
                                <th>State</th>
                            </tr>
                        </thead>

                        @if (ViewBag.Location != null)
                        {
                            foreach (var location in ViewBag.Location)
                            {
                                <tr>
                                    <td>@(x++)</td>
                                    <td>@location.Title</td>
                                    <td>@location.Address</td>
                                    <td>@location.LGA</td>
                                    <td>@location.State</td>
                                    <td>
                                        <a class="btn btn-success btn-xs" data-modal="" href="@Url.Action("Edit", "Location", new { Area = "HRAdmin", id = location.ID})"><i class="fa fa-pencil"></i> Edit </a>
                                        <a class="btn btn-danger btn-xs delete" href="@Url.Action("Delete", "Location", new { Area = "HRAdmin", id = location.ID})"><i class="fa fa-trash"></i> Delete </a>
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

    <!-- modal placeholder-->
    <div id='myModal' class='modal modal-primary fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-content" id='myModalContent'></div>
            </div>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript" src="~/Scripts/modal.js"></script>
        <script type="text/javascript" src="~/Scripts/delete-modal.js"></script>
        <script>
            $(document).ready(function () {
                $('#grid').DataTable({
                    columnDefs: [
                        {
                            targets: [0, 1, 2, 3, 4],
                            className: 'dataTable'
                        }
                    ]
                });
            });
        </script>
    }
</section>